packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/node": "^24.10.1"
  "@types/react": "^19.2.5"
  "@types/react-dom": "^19.2.3"
  "@vitejs/plugin-react": "^5.1.1"
  "@tailwindcss/postcss": "^4.1.18"
  "autoprefixer": "^10.4.20"
  "eslint": "^9.39.1"
  "globals": "^16.5.0"
  "postcss": "^8.5.6"
  "react": "^19.2.0"
  "react-dom": "^19.2.0"
  "tailwindcss": "^4.1.18"
  "typescript": "~5.9.3"
  "typescript-eslint": "^8.39.0"
  "vite": "^7.2.4"
  "rimraf": "^6.1.2"
